export enum AppRoute {
  AUTH = 'Auth',
  SIGN_IN = 'Sign In',
  SIGN_UP = 'Sign Up',
  RESET_PASSWORD = 'Reset Passrord',
  HOME = 'Home',
  TODO = 'ToDo',
  TODO_IN_PROGRESS = 'ToDo In Progress',
  TODO_DONE = 'ToDo Done',
  TODO_DETAILS = 'ToDo Details',
  PROFILE = 'Profile',
  ABOUT = 'About',
  SETTING='Setting',
  MODAL='Diagnosis/Modal',
  CAMERA="Camera",
  SERVICE_ORDER="Profile/SERVICE_ORDER",
  PIECES_BY_TRUCK="Profile/PIECES",
  SIGNATURE="Signature",
  EDIT_SERVICE_ORDER="Home/EDIT_SERVICE_ORDER",
  NEW_SERVICE_ORDER="NEW_SERVICE_ORDER",
  DIAGNOSIS_FILE="DIAGNOSIS_FILE"
}
